[package]
name = "thinker"
version = "0.1.0-beta.5+20230403"
description = "Idea exploration sandbox"
repository = "https://github.com/rushmorem/thinker"
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
